//
//  CropProfileData.swift
//  TeachingGarden
//
//  Created by mac on 12/29/22.
//


import SwiftUI

struct Crop: Identifiable {
    let id = UUID()
    let imageName: String
    let title: String
    let intro: String
    let types: String
    let planting: String
    let fert: String
    let harvest: String
}

struct CropList {
    
    static let CPArr = [
        Crop(
            imageName: "lettuceCrop",
              title: "Lettuce",
              intro: "Lettuce (Lactuca sativa) is a cool-season vegetable that can be planted in early fall or early spring in Alabama. Lettuce enjoys cool temperatures and can even tolerate a light frost, but extremely cold or hot weather will cause it to perish. Choose an area that receives at least eight to ten hours of sunlight per day.",
              types: "Several types of lettuce can be grown in the home garden. Head lettuce such as iceberg lettuce or those found in supermarkets, do not grow well in the hot Alabama climate and should be avoided. Leaf lettuce does well and may come in various colors with leaves that are smooth, round, wrinkled, serrated or curled. Romaine lettuce forms loose upright plants and can be harvested either as whole plants or the outer leaves can be pulled off a little at a time. Bibb lettuce forms small loose heads and has a mild buttery flavor.",
              planting: "Lettuce does well in Alabama in the fall months, but new varieties are being developed to tolerate mild spring months as well. The following dates are good guidelines when planting lettuce in the garden: Jan. 15 -Feb or Aug. 15 -Sept. 1 Lettuce can be either directly seeded or started five or six weeks earlier inside the house or greenhouse. Prepare the garden bed by tilling to a depth of 8 to 10 inches and removing any large soil clods, sticks or stones. Smooth the planting area carefully, as a well-prepared garden bed is essential. Lettuce transplants should be left outside for four to five days to become acclimated to outdoor temperatures prior to planting in the garden. Space plants 10 to 12 inches apart in rows that are 18 to 24 inches apart. Lettuce seeds can be directly planted in single rows. Lettuce seed is very tiny; therefore, do not plant it too deeply. Seed should be worked in under the soil surface to a depth of 1/8 to 1/4 inch deep and the seed bed firmed lightly with your hand or the top of a hoe to allow maximum sunlight for good germination.",
              fert:"Lettuce seed and transplants should be watered frequently the first two weeks to keep the seed bed moist but not waterlogged. This moist establishment period is essential to get the crop up and growing. Continue to irrigate lettuce every four to five days as needed to keep the plants healthy and producing. Lettuce grown in raised beds or containers will need to be irrigated more frequently. Lack of moisture can sometimes cause lettuce leaves to taste bitter. Drip irrigation or soaker hoses are the best way to irrigate, but overhead irrigation can also be used when necessary. Fertilizing is important in the first two weeks of growing lettuce. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer.",
              harvest: "Harvest the older, outer leaves as soon as they are large enough to use. Harvesting can occur as the plants mature. If fully developed plants become too crowded, pull out every other plant to leave more room for the others. Lettuce can be stored in the refrigerator for up to a week. Keep lettuce in bags in the crisper drawer to maintain high moisture."
            ),
       Crop(
        imageName:"gardenpeascrop2",
            title:"Garden Peas",
            intro:"Garden peas (Pisum sativum L.) are cool-season crops that include the common green English pea and the edible-podded pea. English peas are shelled and only the seed eaten, whereas edible-podded peas are eaten whole. Edible-podded peas take two forms, the full-podded snap pea with large seeds and the flat-podded snow or sugar pea with undeveloped seeds. Wrinkled-seeded varieties of peas generally are sweeter than smooth-seeded varieties and are preferred for home use.",
            types:"Garden Peas are one of the easiest types of vegetables to grow in a home garden. Peas should be grown in the cooler climates in Alabama for  crops to produce a large yield of peas, so plan to begin planting your peas in the months of January and February. The following varieties are good starts for growing peas in your home garden: Little Marvel, Green Arrow, Snappy, Victory Freezer, Sugar Snap, or Early Snap.",
            planting:"Directly plant pea seeds 1 to 1½ inches deep and 1 to 2 inches apart in single or wide rows. A single row consists of seeds sown in a straight line, whereas a wide row ranges between 6 and 18 inches in width. The width of a garden hoe blade makes a convenient row width for garden peas. Regardless of row type planted, space rows 2 feet apart. Pea plants, even dwarf varieties, benefit from some type of support, so provide netting, trellis, or wires. Erect the support system before or immediately after planting seeds to avoid disturbing the roots of germinating and established plants.",
            fert:"In the absence of adequate rainfall, water the garden to provide an even supply of moisture to the pea crop. Peas should be watered in the early morning so that the foliage will be dry before dark. Always water plants sufficiently to moisten the soil to a depth of 6 inches, as light sprinklings will encourage shallow rooting of the plants. The critical period for moisture is during early pod set and development. Fertilizing is important in the first two weeks of growing peas, however, since peas are in the legume family and fixate their own Nitrogen, frequent fertilizer applications are not needed as they will cause the plant to grow more vegetative material and offset pea and pod development. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer.",
            harvest:"English peas and snap peas are ready to harvest when the pods become plump, but before each seed is individually visible in the pod and before the pod appears yellow or fibrous. For edible-podded types, harvest when pods are fully developed (about 3 inches), but before seeds are more than 50% of their full size. Wash and cool immediately. Pick snow peas while the pods are quite flat, and the seeds are tiny. This is usually within 7 days from flowering. Overripe snap peas and snow peas can be shelled and used like English peas. Alternatively, overly mature pods of garden peas can be dried and shelled with the dried peas used in soups."
              ),
        Crop(
            imageName: "swisschardcrop",
                title: "Swiss Chard",
                intro: "Swiss Chard (Beta vulgaris) is a colorful and easy-to-grow leafy green. It is the same species as beet, but without the swollen root, and shares the same earthy flavor. The ruffled leaves have stalks of white, pink, gold, orange, or red, depending upon the cultivar. Swiss Chard can be sown directly into the garden in spring or late summer and will take 40 to 45 days to reach maturity. Leaves are harvested individually, in a cut and come again fashion. The culinary uses for Swiss chard are like those of spinach, with the young leaves eaten raw in salads and the mature leaves chopped and cooked in sautés, soups, stews, and sauces. Swiss Chard is a good source of vitamins C, K, A and the minerals iron and magnesium. Swiss chard is also an attractive ornamental plant and can be a complementary companion for pansies, mums, and other flowers in the landscape or a container.",
                types: "There are many varieties of Swiss Chard that are all suitable for home gardens in Alabama. Swiss Chard usually comes in the following categories: Mixed, Red, or White. Mixed: Bright Lights, Red: Burgundy, Rhubarb, Ruby, White: Fordhook, Winter King",
                planting: "Swiss chard requires eight to 10 hours of sunshine per day, so be sure to choose a sunny location in your garden. Prepare the bed by loosening the soil to a depth of 10 inches. Discard weeds, rocks and roots, and break up big clods of earth. Sow the seeds as soon as the soil is workable. In rows, sow the seeds 1 inch apart, with 12 to 15 inches between the rows. In raised beds, sow the rows 8 to 10 inches apart. In both cases cover the seeds with 1/2 inch of soil. Thin the seedlings 4 to 6 inches apart as soon as they are large enough to be pulled out.",
                fert: "In the absence of adequate rainfall, water the garden to provide an even supply of moisture. Always water plants sufficiently to moisten the soil to a depth of 6 inches, as light sprinklings will encourage shallow rooting of the plants. Fertilizing is important for the development and taste of Swiss Chard, as stressed or nutrient deficient plants will taste bitter. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer.",
                harvest: "Remove mature, outer (oldest) leaves by cutting or breaking stems 1 inch above the soil line, or harvest “baby” leaves for salads. Chard may be harvested continuously until flowering. Swiss Chard can be stored in a plastic bag in the refrigerator for up to 2 weeks."
           ),
        Crop(
            imageName: "radishescrop",
                title: "Radishes",
                intro: "Radishes (Raphanus sativus) are fairly easy to grow. Radishes can be planted for both spring and fall crops in Alabama. They mature anywhere from 21 to 30 days from seeding, depending on soil and air temperatures during their growing time. For radishes, the warmer it is, the faster they mature. Radishes prefer cool and moist conditions for best growth. The optimum temperature is 50 to 65 °F. Optimum soil temperature for seed germination is 45 to 85 °F. Radish seed will not germinate when the soil temperature is above 95 °F",
                types: "Due to the short time from seeding to harvest, radishes can be a fun crop to plant with young children. There are a few good varieties of Radish to consider growing in your home garden: Cherry Belle, Scarlet Globe, White Icicle. Any of these varieties can be grown during the following months: February 1-April 1 or September 1- October 15.",
                planting: "Plant radish seed in rows 12 to 24 inches apart and place the seed ½-inch deep with about 1 inch between seeds. Radish can be broadcast-seeded in a 12-inch bed and then thinned to 2 to 3 inches apart when plants are in the one to two “true leaf” stage, about 2 inches tall. Radishes are some of the fastest germinating seeds and should emerge in just a few days. Plant every seven to 10 days during the recommended planting periods for a continuous supply of radishes.",
                fert: "Water the garden to provide a uniform moisture supply to the crop. The garden should be watered in the morning so that the foliage is dry before dark. Water the garden sufficiently to moisten the soil to a depth of 6 inches. The critical periods for water are during stand establishment and root development. Moisture stress during development of the radish will cause it to have a strong flavor and be woody or pithy. Fertilizing is important for the development and taste of Radishes, as stressed or nutrient deficient plants will taste bitter. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer.",
                harvest: "Radishes will be ready to harvest in about 3 to 4 weeks after planting. These plants develop very rapidly; therefore, check the plantings frequently to prevent them from becoming too large to use. The round red radish should be harvested before it is an inch in diameter. Larger radishes will usually have a strong flavor and will be pithy. White radishes should be harvested before they are about ¾ inch in diameter. Radishes can be stored in the refrigerator for about two weeks."
           ),
        Crop(
            imageName: "mustardcrop",
                title: "Mustard",
                intro: " Mustard (Brassica juncea) is a versatile species grown for its spicy leaves and seeds. Mustard cultivars have green or red-tinged leaves that range in size and texture from flat to curled and entire to deeply lobed. Spring plantings may bolt with warmer temperatures. While fall plantings are tolerant of frost, they may be damaged by a hard freeze. Mustards reach maturity between 25 to 50 days from sowing, depending on the cultivar. Because of their frost tolerance, mustards are also used as ornamental plants in borders or containers.",
                types: "Due to warmer temperatures and an increase in bolting of mustard greens, there are a few recommended varieties that Alabama gardeners can enjoy: Florida Broadleaf Giant Southern Curled Red Giant",
                planting: "Plant seeds 4 to 6 weeks before the last frost in spring and 6 to 8 weeks before the first frost in fall. Several plantings, a couple of weeks apart, provide a continuous supply of mustard. Harvest by cutting entire plants, breaking off only the large leaves, or cutting plants to within an inch or so of the crowns, permitting regrowth for a second harvest. Curly leaved varieties trap a lot of sand that is difficult to wash off. Planting dates can vary depending on your location, but these are typical guidelines when planting mustard seeds in Alabama: Feb. 1 - Mar. 15, Aug. 15 -Sept. 5 ",
                fert: "Direct seeding works well when planting in late summer for a fall harvest, when the soil is much warmer. It is critical to keep the soil moist during seedling establishment. Plant seed in moist soil about ¼ to ½ inch deep. Seeds planted deeper than ½ inch likely will not germinate. Thin plants to the desired stand when they are in the three-leaf stage.Fertilizing is important for the development and taste of Mustard Greens, as stressed or nutrient deficient plants will taste bitter. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer. ",
                harvest: "Most cultivars have the flexibility to be harvested as microgreens, baby leaves, or mature bunches. Greens can be harvested in a cut-and-come-again method, known as cropping, by removing the outermost leaves and leaving the center of the plant to continue growing. Greens are best when consumed within a week after harvest and can be stored in a plastic bag in the refrigerator."
           ),
         Crop(
            imageName: "turnipcrop",
                title: "Turnips",
                intro: "Turnips (Brassica rapa) are generally tolerant of freezing weather, and their roots can be stored for a fairly long period of time in cold storage conditions. Turnips have a crisp white flesh and a zesty mustard-like flavor. Turnip is a dual purpose crop—the leaves are used for greens, and the root is cooked similar to potatoes and beets. When cooked properly, turnip greens are high in minerals and vitamins A and C.",
                types: "Although these crops will stand some heat, they are normally considered cool-weather crops. Plant them in late winter/early spring for a spring crop or in the late summer for a fall/winter crop. The seeds of turnip and rutabaga are very small. Varieties suited well for Alabama gardens include: Purpletop, Shogoin, Just Right (roots). ",
                planting: "Plant turnips as soon as the soil can be worked in the spring. The seeds will sprout if the soil temperature is 40 degrees F or higher. Turnips can be planted in Alabama during February-March and August to October. ",
                fert: "If the weather is dry, irrigation during the root development stage will give the best quality roots.It is critical to keep the soil moist during seedling establishment. Plant seed in moist soil about ¼ to ½ inch deep. Fertilizing is important for the development and taste of Turnips, as stressed or nutrient deficient plants will taste bitter. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer.",
                harvest: "Turnip tops can be harvested from a very early stage for greens. Harvest turnip roots when they reach the size of a tennis ball or larger (2½ to 2¾ inches in diameter). Greens are best when consumed within a week after harvest and can be stored in a plastic bag in the refrigerator."
           ),
         Crop(
            imageName: "carrotcrop",
                title: "Carrots",
                intro: "Carrots (Daucus carota) are cool-season plants that grow best at average temperatures between 60 and 65 °F. The optimum soil temperature for seed germination is 55 to 75 °F. Seeds will not germinate above 95 °F. It is important to plant carrots early enough in the spring to ensure that the crop is harvested before early summer. Carrots near maturity that are allowed to remain in the garden under high temperature conditions tend to develop a strong flavor and roots that are coarse and fibrous.",
                types: "There are many varieties of carrots suitable for Alabama gardens. Most gardeners plant carrots in the early spring months of March. The following are suggested varieties of carrots to grow in Alabama: Chantenay, Danvers 126, Lady Fingers, Scarlet Nantes, Thumbelina ",
                planting: "Carrots prefer a good-textured, loamy or sandy soil that is free of stones and clods. When grown in heavy clay soils, the carrot roots will grow poorly, and they may be forked or misshaped. Plant carrots in rows 12 to 18 inches apart with a quarter-inch between the seeds. Carrot seeds are very small, and it is difficult to obtain a stand if the soil is crusty. Try mixing carrot seed with dry sand to get even distribution. Then, instead of covering with soil, cover the seed 1/8-inch deep with sawdust, vermiculite or manufactured potting soil. Water the row soon after planting is complete. This method will allow the seeds to stay wet and prevent crusting. Thin the carrots to 2 to 3 inches between plants when they are 1 to 2 inches tall.",
                fert: "Water the garden to provide a uniform moisture supply to the crop. Water the garden sufficiently to moisten the soil to a depth of 6 inches. The critical periods for water are during stand establishment and root development. If a uniform supply is not provided for carrot growth, then cracks, strong flavor, and coarseness in the roots may develop.Fertilizing is important for the development and taste of Carrots, as stressed or nutrient deficient plants will taste bitter. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer.",
                harvest: "Harvest carrots about 65 to 75 days after planting. Carrots should be harvested when they reach the desired size. Store them at 33 °F and high humidity to prevent wilting. Bunched carrots (plants with tops on) can be stored for about 10 to 14 days. Carrots with tops removed can be stored for four to six months under optimum conditions."
           ),
         Crop(
            imageName: "collardscrop",
                title: "Collards",
                intro: "Collards (Brassica oleracea) can be grown most of the year in Alabama, though early spring or fall production is generally preferred. Mature plants will withstand frosts and light to medium freezes. Collards may be grown in a variety of soils. In the spring, select a bolting tolerant cultivar, meaning it will not readily develop a flower head when exposed to cold following a favorable growing period. Eventually, any cultivar will bolt with hotter temperatures. ",
                types: "Most collard cultivars are bred to be slow to bolt. The cultivars listed below are just a few of many good available options. Hybrids:Blue Max, Flash, Top Bunch 2.0 ,Tiger, Champion. Heirlooms: Georgia Southern, Morris Heading, Vates ",
                planting: "Transplants are the preferred planting material for a spring crop, as seeds germinate slowly in cool soil in the spring. Start seeds indoors six to eight weeks prior to the desired planting date. Plant collards in rows that are 18 to 36 inches apart. Space plants 6 to 18 inches apart on the row. Direct seeding works well when planting in the late summer for a fall harvest, as the soil is much warmer at this time. It is critical to keep the soil moist during seedling establishment. Plant seed in moist soil about ¼ to ½ inch deep. Seeds planted deeper than ½ inch likely will not germinate. Thin plants to the desired stand when they are in the three-leaf stage. Typically, Collards in Alabama are grown during the late summer and early fall months for maximum yield. Planting dates in Alabama are usually between July 1- September 15. ",
                fert: "Collards require moderate amounts of fertilizer. Nitrogen is essential for collards to produce high-quality leaves. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer. Water the garden to provide a uniform moisture supply to the crop. Leaves will become wilted and limp when soil moisture is insufficient. Water early in the day to allow the leaves to dry before nightfall. This will aid in avoiding foliar plant diseases. Water sufficiently to moisten the soil to a depth of at least 6 inches, as light sprinklings will encourage shallow rooting. The critical periods for moisture are at stand establishment and crop maturation. Mulching can help conserve water and reduce weeds.",
                harvest: "Collards should be ready for harvest 60 to 80 days after direct seeding, depending on the cultivar. Microgreens will be ready to harvest 10 to 15 days after seeding. Entire plants may be cut when half-grown or full-grown. To extend the harvest, break off individual leaves starting from the bottom of the plant and move up over time. Pick only a few leaves from each plant to give the plant time to recover. Collards can be stored in a plastic bag in the refrigerator for up to 2 weeks."
           ),
           Crop(
            imageName: "asparaguscrop",
                title: "Asparagus",
                intro: "Asparagus (Asparagus officinalis) is a hardy perennial that is native to the Mediterranean. Once the plants are established, they will provide delicious spears every spring. Although asparagus takes two to three years to begin production, it will be highly productive for seven to eight years before gradually declining.",
                types: "When planting asparagus, it is important to note that you will plant “crowns” rather than seeds. Crowns look similar to a root structures of plants, but this is the primary method of growing asparagus. In Alabama, there are a few recommended varieties that can be planted successfully: Mary Washington (female hybrid), UC-157 (male hybrid), Jersey Giant (male hybrid)",
                planting: "Choose a site for a permanent asparagus bed that has good drainage and full sun. Plan accordingly as the tall ferns of asparagus may shade other plants. Bed preparation is best done in the fall. Start asparagus from 1 to 2-year-old disease-free crowns. If the crowns are planted too late in the spring, they may begin sprouting before planting, which can injure the developing buds. Typical planting dates in Alabama are in April after any threat of a late frost.",
                fert: "Nitrogen, phosphorus, and potassium are all important at planting and throughout the entire life-span of asparagus. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer. Adequate soil moisture is important to keep young plants growing rapidly. Good growth in the first year is important for large crowns. During the period of stand establishment, they should not be water-stressed or over-watered. Water sufficiently to moisten the soil to a depth of at least 6 inches. Light watering will lead to shallow rooted plants. ",
                harvest: "Depending on the variety, asparagus crowns may need two to three full growing seasons before limited harvesting can be done in the third or fourth year. The fleshy root system needs to develop and store food reserves to produce growth during subsequent seasons. In all asparagus planting, cut the foliage down to 2-inch stubs in late winter after they turn brown, but before the spears emerge in spring. Letting the ferns turn brown allows nutrients to be exported from the foliage into the crowns for next year’s growth. After harvest, process or refrigerate immediately. Asparagus can be frozen or canned. Asparagus has an attractive, fern-like foliage that makes a nice garden border. Some gardeners prefer to support the growing foliage with stakes and strings to keep them tidy. In high-wind areas, plant the rows parallel to the prevailing winds so that the plants support each other to some extent."
           ),
           Crop(
            imageName: "broccolicrop",
                title: "Broccoli",
                intro: "Broccoli (Brassica oleracea) is a cool-season vegetable that can easily be grown in the home garden. The crop prefers average temperatures of 65 to 75 F and is best grown in Alabama during the fall season. While broccoli will produce in the spring season, temperature fluctuations can cause quality issues such as uneven heads and loose clusters of buds. Commercially, these heads are unmarketable but are suitable for home consumption.",
                types: "The broccoli Broccoli can be direct seeded or started indoors for transplants. Spring plantings should be made 2–3 weeks before the last frost date in your area and Fall plantings should be made approximately 100 days before the first Fall frost. Sow seed 1.3 cm (0.5 in) deep in small groups of 2–3 seeds and about a week after emergence, thin to a final spacing of 30–60 cm (12–24 in) within the row, allowing 90 cm (36 in) between rows. Keep soil evenly moist after planting. If starting indoors, plant seed in peat pots to minimize disturbance to the roots when transplanting. Seedling can be planted outdoors when they are 3–4 weeks old at the same time as seeds are planted using the spacing detailed above. Plant transplants slightly deeper in the ground than they currently are in their pot and keep soil moist to ensure good fertility.",
                planting: "Broccoli can be direct seeded or started indoors for transplants. Spring plantings should be made 2–3 weeks before the last frost date in your area and Fall plantings should be made approximately 100 days before the first Fall frost. Sow seed 1.3 cm (0.5 in) deep in small groups of 2–3 seeds and about a week after emergence, thin to a final spacing of 30–60 cm (12–24 in) within the row, allowing 90 cm (36 in) between rows. Keep soil evenly moist after planting. If starting indoors, plant seed in peat pots to minimize disturbance to the roots when transplanting. Seedling can be planted outdoors when they are 3–4 weeks old at the same time as seeds are planted using the spacing detailed above. Plant transplants slightly deeper in the ground than they currently are in their pot and keep soil moist to ensure good fertility.",
                fert: "Broccoli is a heavy feeder of fertilizers. Nitrogen is essential to produce high-quality, productive broccoli plants. Magnesium deficiency is a problem on broccoli leaves during cool, wet periods and is characterized by interveinal chlorosis (yellowing between leaf veins) on older leaves. Correct this deficiency by spraying Epsom salts mixed at two tablespoons per gallon of water directly onto the plant. Repeated applications over a period of weeks may be necessary to correct the deficiency. Water the garden to provide a uniform moisture supply to the crop. The garden should be watered in the morning so that the foliage is dry before nightfall. Water sufficiently to moisten the soil to a depth of at least 6 inches. Light sprinklings will encourage shallow rooting of the plants. The critical periods for moisture are during stand establishment and head development. It is important to have a consistent and uniform moisture supply to produce high-quality broccoli and to have the spring crop mature before summer temperatures arrive.",
                harvest: "Broccoli is ready to harvest 50 to 90 days after transplanting, depending on the variety. Harvest broccoli when the main head is 3 to 6 inches in diameter, and the flower buds are still tightly closed. Cut the main stem about 6 inches below the top of the head. Some varieties produce many secondary florets in the axils of the stems after the main head has been harvested. Store in perforated plastic bags for up to a week in the refrigerator and freeze any surplus."
           ),
           Crop(
            imageName: "brusselsproutscrop",
                title: "Brussel Sprouts",
                intro: "Brussels sprouts belong to the cole crop family, which includes cabbage, broccoli, cauliflower, and several leafy greens. The name Brussels comes from the city Brussels, Belgium, where the vegetable first became popular. Brussels sprouts are a cool season vegetable that can be grown both in the fall and early spring. They also take a long time to mature, which can make them a little bit of a challenge for the home gardener. For ease of growth, select and use transplants that are young and vigorous. ",
                types: "It is important to choose the best variety available when looking to grow Brussels sprouts. Varieties such as Jade Cross E, Long Island Improved, Prince Marvel, and Valiant have a 90 day maturity rate. Jade Cross E has large sprouts and is easy to harvest. Long Island Improved is open-pollinated and is an old-time variety. Royal Marvel has 85 days to maturity, is very productive, and has tight sprouts. ",
                planting: "Like most vegetables, Brussels sprouts require a minimum of six hours of sunlight daily. They prefer a fertile, well-drained, organic soil but will tolerate a wide range of soils. Brussels sprouts grow best when planted as transplants in late summer or early spring. You should plant Brussels sprouts 15 to 18 inches apart in rows with about 30 inches between rows. The best time to plant Brussels Sprouts in Alabama in from August 1-15th.",
                fert: "Brussels sprouts are fairly heavy feeders, so they will need a heavy fertilization at planting time and several other applications evenly spaced out during the growing season to keep them producing. Irrigate Brussels sprouts frequently enough to keep the soil slightly moist, particularly during warmer periods of plant development. Mulching around plants with straw or wood chips will help conserve moisture and also reduce weed competition.",
                harvest: "When temperatures get too warm, Brussels may become bitter. When the tops of the plants reach a height of 24 inches or more, pinch out the top portion of the plant to aid in forcing more energy down into the plant and into the Brussels sprouts themselves. These plants are cold hardy and can withstand a freeze. They can also be left on the plants and harvested on an as needed basis throughout the winter. Brussels sprouts should be harvested as soon as their diameter is large enough (when they reach 1.5 to 2 inches in diameter or the size of a quarter). Remove them by twisting them off the plant, which will help prevent damaging the edible portion of the fruit, starting from the bottom and working your way upward. Remove some of the bottom leaves and stems as you harvest your way up the trunk. Continue to harvest Brussels sprouts in this manner all the way through the growing season. Store harvested Brussels sprouts in the refrigerator until they are ready to be cooked. They can also be frozen."
           ),
           Crop(
            imageName: "bokchoycrop",
                title: "Bok Choy",
                intro: "Chinese vegetables include Chinese cabbage, bok choy, mustard greens, winter radish, snow peas, yard-long beans, and varieties of melons, eggplant and cucumbers, among others. These vegetables are becoming more familiar to an increasingly diverse population and the popularity of ethnic foods. Many Chinese vegetables will grow well in the home garden. Bok Choy (Brassica chinensis) has many names including pak choy, bok-choi, celery mustard and spoon cabbage. They form loose upright heads with dark green leaves and thick, crisp, white or pale green ribs. Most varieties are bolt-resistant.",
                types: "‘Joi-choi’ is vigorous, uniform and slow-bolting. The plants are upright with dark green leaves, ivory stems and fine, spoon-shaped stalks. ‘Joi Choi’ is very tolerant of cold weather. ‘Chin-Chiang’ is a fast-growing baby bok choy that is resistant to high temperatures and matures in 30 days. ‘Mei Qing choi’ is a baby bok choy with light green stems and paddle-shaped leaves.",
                planting: "Cole crops should be grown in early spring or fall. If planting in spring, it is essential to plant early enough to ensure that the crop is harvested before temperatures become too hot. Most will bolt (produce a flower stalk) if exposed to a prolonged cold period following a favorable growing period. Oriental Cabbages are usually planted in Alabama during early spring or late fall when the weather is much cooler.",
                fert: "These vegetables grow best with uniform soil moisture. Water the garden in the morning so that the foliage is dry before dark. Water sufficiently to moisten the soil to a depth of at least 6 inches. Avoid light sprinklings, which encourage shallow rooting. The critical periods for moisture are stand establishment and crop maturation. Mulching can help conserve water and reduce weeds. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer.",
                harvest: "Harvest about a month after sowing, when they are about 1 foot tall. Entire plants may be harvested to thin the crop and give remaining plants more room. Bok choy will bolt (go to flower) quickly if not harvested. Store harvested Bok Choy in the refrigerator until it is ready to be cooked."
           ),
           Crop(
            imageName: "cabbagecrop",
                title: "Cabbage",
                intro: "Cabbage (Brassica oleracea var. capitate) is a popular cool-season vegetable that is a member of the cole crop family. There are several types of cabbages available to grow, and they can all be eaten raw or cooked in a variety of ways.",
                types: "Cabbage can be divided into two major types: standard round head cabbage and Chinese cabbage. Chinese cabbage is more upright and the leaves are somewhat thinner than standard cabbage. All of them are planted in the same manner. Varieties of standard round head cabbage to be grown in Alabama include: Bravo, Charleston Wakefield, Round Dutch, Stonehead Savoy Cabbage: Ace. Cabbage can be planted in January-February and Mid-late August in Alabama.",
                planting: "Cabbage does best when planted in the early spring, but it can also be planted in late summer for a fall harvest. In Alabama, fall cabbage does a little better because it is maturing when temperatures are decreasing, and disease risk is a little lower than it is during the spring. Because cabbage matures in a fairly uniform manner—the heads will mature at the same time—stagger plantings a week or two apart for several weeks. This will provide a longer harvest season. Although cabbage can be planted directly from seed, gardeners generally have greater success using transplants. Transplants can be grown indoors six to eight weeks prior to planting. Transplants are also available for sale in the spring and fall in most garden centers. Cabbage can tolerate light freezes, but sustained temperatures below freezing can damage it. Choose a location that receives at least eight hours of sun in an area with well-drained soil. Cabbage also grows well in raised beds.",
                fert: "Cabbage is a fairly heavy water user and will need irrigation on a regular basis. In the absence of rain, supply approximately 1 to 2 inches of water per week. Irrigate in the early morning to cut down on evaporation and to allow the foliage to dry during the day. Mulch will also help keep soils moist and cut down on evaporation. Water-soluble fertilizers such as Miracle Gro® Plant Food can be used as an effective and inexpensive fertilizing method for a healthy crop. Just be sure to follow the label and instructions for how to mix and use any fertilizer.",
                harvest: "Depending on the variety, cabbage should be ready to harvest in 45 to 85 days. Harvest the heads when they have achieved full size and are firm to the touch. Leaving cabbage heads in the garden too long can cause them to split. Remove them from the plant by cutting them with a sharp knife at the base of the stalk. Store harvested cabbage in the refrigerator for up to four months."
           ),
           Crop(
            imageName: "cauliflowercrop",
                title: "Cauliflower",
                intro: "Cauliflower (Brassica oleracea var. botrytis) is the same species as broccoli, cabbage, Brussels sprouts and turnip, and has many similar needs for good garden performance. For the best quality cauliflower, grow it in rich, moist soil without drought stress. The dense, mounded head of cauliflower is the “curd.” The curd is the flowering stalk of the plant. The edible stage is before the flowers open. For those who love it, nothing is better than the richness of cauliflower in an Indian curry, a North African stew, or a creamy soup. In many kitchens, raw on a vegetable platter, steamed as a side dish, baked in a cheesy casserole, or pickled and served with a sandwich are all common recipes.",
                types: "nil",
                planting: "For spring-planted cauliflower, it is best to plant in early to mid- April. Choose a variety with heat tolerance and a short growth cycle (50 to 60 days to harvest). ‘Snow Crown’ is one of the best for spring growth.For the fall crop, start seeds indoors or direct seed in the garden, in early to late July. Whether you plant in spring or summer, a row cover will protect the plants from wind and insects during the first weeks of growth. In spring, use a cover material that will give protection against cold. In summer, use a lightweight material so that temperatures do not get too hot under the cover.",
                fert: "Cauliflower needs good soil moisture. To produce hard, solid, rich-flavored heads, the plants must not experience water stress. If the plants do not receive consistent rainfall or irrigation, they will have poor texture and may develop strong “off” flavors. If the planting does not receive one inch of rain each week, soak the soil thoroughly at least once a week. If your soil is sandy, it is important to water more often than once a week. An inch of water will wet a sandy soil to a depth of ten inches, a heavy clay soil to a depth of six inches. Use a trowel to see how far down the soil is wet. If it is only an inch or two, keep the water running. Grow cauliflower in well-drained yet moisture-retentive, fertile soil with pH of 6 to 7. A good cauliflower crop needs this ideal garden soil.It is not worth growing cauliflower unless the plants absorb water and nutrients steadily during their growth. Improve your soil by adding well-rotted manure or compost in spring or fall. Do not use fresh manure as it may contain harmful bacteria and increase weed problems. If you use manure or compost, you may not need more fertilizer applications, depending on how much organic matter you use. Side-dress when the plants are about four inches tall.Do not use any fertilizer containing a weed killer (\"Weed and Feed\"), as it may kill your vegetable plants.",
                harvest: "Harvest cauliflower when heads reach usable size, before the flower buds open. Cut the head above ground level and remove the leaves wrapped around the head. If you leave curds on the plant for too long, they will become loose, especially in spring plantings. Colder fall weather helps the later crop hold its quality in the field. Cauliflower will keep for about one week in the refrigerator. Even in colder, moist conditions, it will not keep more than three weeks.Preserve a big harvest by freezing cauliflower or you can also pickle cauliflower in a mix of vegetables."
           ),
           Crop(
            imageName: "onionscrop",
                title: "Onions",
                intro: "Onions (Allium cepa) have relatives that include garlic, chives, leeks and shallots. Yellow, white, and red/purple onions grow very well in home gardens. Green onions may be eaten fresh or chopped and added to salads. Bulb onions may be sliced and used on sandwiches or dipped in batter and fried as onion rings. Although onions are a source of vitamins A and C, they are used mostly as a flavoring in other food dishes.",
                types: "Planting the right varieties in a particular area determines whether or not onions form bulbs. When onions are first planted, their growth is concentrated on roots and green leaves or tops. Onions start to form bulbs when a particular combination of daylight and darkness occurs. This is referred to as day length or photoperiod needs of an onion variety. In Alabama, you can plant short-day varieties from late fall to early winter, which stimulates the formation of bulbs when day length is at its shortest. Long Day onion varieties, like ‘Walla Walla’ for example, are planted in the northern United States in late spring, growing at a time when day length is at its longest. Storage onions: The most obvious difference between storage and fresh onions is that storage onions keep for a longer period of time. Storage onions generally have a darker color, thicker skins, and a more pungent flavor than fresh onions. Storage onions can be grown from seed, onion sets, or transplants. Sets are generally sold as yellow, white, or red onions, not by a variety name. Fresh onions: As the name implies, fresh onions are not good keepers and are best eaten soon after they are harvested. Fresh onions are also commonly referred to as sweet onions. The most famous fresh “sweet” onion is the Bermuda onion. It is the grandfather of all of the sweet onions on the market today. Sweet fresh onions are not grown from sets. They must be planted from seed or transplants. Look for the fresh sweet onions under variety names such as yellow or white Bermuda, Excel, Texas Grano 502, Texas Grano 1015, and Texas Granex 33 (commonly sold under the name “Vidalia” onion). Bunching or multiplier onions (also called green onion, Welsh onion, Japanese onion and scallions) produce continuous clusters of small pearl type onions. To grow them from seed, plant in late winter to early spring for an early summer harvest, and in fall for late winter, early spring harvest. Sets should be planted in the fall. Once you have established some clumps, simply harvest as needed, divide clumps, and replant for the next crop. Varieties to plant include Evergreen White Bunching and Beltsville Bunching.",
                planting: "Onions can be grown from seeds, small dormant onions called “sets,” or onion transplants. Onion seeds should be sown in the garden in the fall (October). However, onion seedlings are easier to grow in a soilless mix where conditions can be controlled. Sow seeds about 1⁄4 inch deep, covering lightly with a soilless mixture. Uniform moisture and a temperature of 70 to 75°F should be maintained. Seed should germinate in 10 to 14 days. Grow onions in individual cell packs to reduce transplant shock. Seedlings should be grown in a cool location in full sun. Transfer onion transplants into the garden when they reach pencil size in diameter (about ¼ inch). Onions may be transplanted from December to February. To reduce risk of loss from freeze damage in colder areas of Alabama, set onions in January to early February. Set plants 1 inch deep, and about 3 to 4 inches apart",
                fert: "Watering is critical to the development of onions. Onions should receive about 1 inch of water per week (2 inches in sandy soils). Water slowly and deeply to produce healthy onions. In the absence of a soil test, apply a complete fertilizer such as 8-8-8 or 10- 10-10, a few days before planting. Onions are heavy nitrogen feeders early when producing roots and top growth. Sidedress about 4 to 6 weeks after planting with a high nitrogen fertilizer (do not use a sulfur product). Sidedress onions one more time about 1 month later in late winter. Later applications of nitrogen can delay maturity of bulbs, cause thick necks and bulb splitting.",
                harvest: "One limitation on storing onions can be the climate in Alabama. Humid, moist conditions may prevent drying and curing onions for storage. Onions will store better if they are dried for several days outdoors, away from direct sunlight. Leave tops on bulbs during drying. After drying, cut tops within an inch of bulb. Fresh sweet onions can be stored for several weeks in a cool, dark place. They can be stored in the refrigerator, but do not put them in plastic bags. This will inhibit air circulation. Storage onions should be dried for a longer period of 10 to 14 days. After cured, the tops can be removed and onions stored in mesh bags, or dried tops can be braided into a string of onions. Depending on the variety, storage onions will remain firm and flavorful if kept in a cool, dry place (32 to 45°F) for 3 to 6 months or more."
           ),
           Crop(
            imageName: "strawberrycrop",
                title: "Strawberry",
                intro: "Strawberry is the name given to several plant species in the genus Fragaria, including Fragaria vesca (wild strawberry), Fragaria grandiflora, Fragaria magna, Fragaria chiloensis and Fragaria ananassa (or Fragaria x ananassa) which are grown for their edible fruit. Strawberry is an herbaceous perennial in the family Rosaceae. The plant has a short stem and trifoliate leaves which form a crown. close to the ground. The leaves display a variety of characteristics depending on the species, some are evergreen whereas some have leaves that will die and fall off in winter. The plant produces flower stalks from the crown and the flowers are white in color. The fruit of the plant is red and fleshy with small seeds on the outside. Strawberries can grow 20–25 cm (8–10 in) in height and have an economic life of 2–4 years before the plants are replaced. Strawberry may also be referred to as garden strawberry and the plant is grown in most northern temperate regions of the world.",
                types: "Based on their photoperiodic nature, there are currently three types of strawberries: spring-bearers, everbearers, and day-neutrals.  Spring-bearing types are typically planted in the spring, de-blossomed the first season, and cropped the second season. Their growth is phasic in that they flower, fruit, and produce runners, in that sequence. Examples of springbearers would include such cultivars as Earliglow, Allstar, and Chandler. Everbearing types flower, produce fruit, and then initiate flower buds under the long days of summer. These plants produce two main crops of relatively poor quality fruit in one season and frequently their total combined yield of the spring and fall crops does not equal the yield of the single crop from a spring-bearer. Examples of everbearers would include cultivars such as Fort Laramie, Ogallala, and Ozark Beauty.  The day-neutral strawberry will flower, produce fruit, and produce runners simultaneously. Under Alabama conditions day-neutrals produce a spring crop and a smaller fall crop when air temperatures fall below 80 °F. Examples of dayneutrals would include cultivars such as Tribute, Tristar, and Selva.",
                planting: "Strawberries need full sun for maximum production and should not be planted near wooded areas that will shade the planting. Sites for planting strawberries should be in areas where adequate air and water drainage occur. Sites lower than surrounding land may be subject to frost damage, because cold air is denser than warmer air and settles in low areas (frost pockets). Avoid soils previously planted with solanaceous crops (tomato, potato, pepper, eggplant) as planting sites unless they can be fumigated. Soils previously planted with solanaceous crops may contain a persistent fungal organism that causes Verticillium wilt. Avoid sites recently planted to sod because they may contain large numbers of white grubs, which are injurious to strawberry roots. Also, perennial weeds are frequently a problem on sites that have previously ARCHIVE 4 Alabama Cooperative Extension System been in sod or pasture.",
                fert: "An adequate and reliable water source in close proximity to the planting is essential for irrigation and for frost protection. This factor should be carefully considered during the site selection process. Irrigation ensures a good plant stand, maximizes plant growth, increases berry size and total yields, and extends the harvest season by ensuring an adequate moisture supply at all times.",
                harvest: "Generally, berries ripen within 28 to 30 days (as few as 20 days under optimum conditions) after first bloom. Proper picking, grading, and packing are as essential as good cultural practices to success. The harvest frequency and duration depend on weather conditions, cultivars, soil factors, and cultural practices. Strawberries are almost entirely hand picked. Harvested berries should be delivered and sold within 24 hours of harvest to reduce spoilage. Berries do not improve in quality after picking. The berries must be picked at the proper stage of ripeness (maturity). Harvest only those berries that are red. Berries still showing white should be left for the next picking. All ripe fruit should be removed to reduce disease problems. The fruit is  usually harvested every other day. Quickly place harvested berries in a cool, shady location such as a temporary field shed. The life of strawberry fruit after harvest is short because of the high rate of respiration. Firm berries, if precooled to below 40 °F will do well at roadside markets. Berries stored for 7 days at 30 °F will be attractive after remaining  at room temperature for 6 hours. "
           ),
           Crop(
            imageName: "bellpeppercrop",
                title: "Bell Pepper",
                intro: "Peppers (Capsicum annuum) are warm-season plants that grow best at temperatures of 70 to 85 °F during the day and 60 to 70 °F during the night. Peppers generally require a long growing season and grow very slowly during cool periods. Therefore, after the soil has thoroughly warmed in the spring, set out 6 to 8 week-old transplants to get a head start toward harvest. Do not plant peppers in the garden until after the last chance of frost. Start seed indoors six to eight weeks prior to this date. ",
                types: "There are two major types of peppers: sweet and hot. Their pungency is actually found in the seed, and it is measured according to the Scoville Heat Index. The mildest peppers such as sweet bell peppers, banana peppers and cherry peppers are at the bottom of the Index. In the middle are serrano, red cayenne and yellow hot wax peppers. At the top of the scale are the habanero and chili peppers.Peppers are classified according to their degree of hot or mild flavor. Mild peppers include bell, banana, pimento, and sweet cherry. Hot peppers include the jalapeno, habanero, cayenne, large cherry, and tabasco.The heat of peppers is measured by the Scoville Heat Scale, which uses Scoville Heat Units (SHU)to represent capsaicin content. The higher the number of SHU, the hotter the pepper is. Jalapeno peppers range from 2,500 to 8,000 SHU while the hottest pepper in the world (as of 2020) with an average of 1.64 million SHU is the Carolina Reaper, which was bred in Rock Hill, SC.",
                planting: "Peppers require moderate amounts of fertilizer. A soil test is always the best method of determining the fertilization needs of the crop. Follow the results of a soil test to maintain a soil pH between 6.0 and 6.5.Apply preplant fertilizer according to soil test recommendations. Broadcast the fertilizer evenly and incorporate it into the soil by tilling or disking to a depth of around 6 inches. Working the fertilizer into the soil ensures that the nutrients are available to the plants when they are seeded or transplanted. Side dress 5 pounds of calcium nitrate (15.5-0-0) per 1000 square feet or 300 feet of row three to four weeks after planting. For smaller gardens, use ½ pound of calcium nitrate fertilizer per 100 square feet or 30 feet of row. A pint is roughly equal to a pound for most fertilizers. Side dress another 5 pounds per 1000 square feet or ½ lb per 100 square feet three to four weeks after that. To avoid burning the roots, place side-dress fertilizer 4 to 6 inches away from the plants. If fertilizer is broadcast, avoid burning the plant foliage by watering overhead after the application to wash the fertilizer granules off the leaves. Water the garden to provide a uniform moisture supply to the crop. Water sufficiently to moisten the soil to a depth of at least 6 inches. The critical period for moisture is during fruit set and fruit development. During fruit development, maintain uniform soil moisture and do not allow the soil to dry out in between watering. Mulching can help to retain consistent soil moisture, conserve water, and reduce weeds.",
                fert: "nil",
                harvest: "Peppers are usually ready for harvest 70 to 85 days after installing a transplant. Bell peppers can be harvested green, when they reach full size and the walls are firm. Cut the stems instead of pulling them to avoid breaking branches. When green bell peppers are left on the bush after reaching full size, they will change to a red color. These will be sweeter in taste than the green peppers. Hot peppers, except for jalapenos, should be allowed to ripen on the bush. They should be harvested when they reach their final dark red color. Store peppers in the refrigerator. They can be stored for two to three weeks in 45° F with 80 to 90 percent relative humidity. Bell peppers can also be frozen. Cut them into strips, spread them out on a tray, and then freeze them. After they are fully frozen, move them into plastic bags, and store the bags in the freezer. To dry peppers, pull the whole plant just before the first frost and hang it upside down. Protect your hands with gloves when handling hot peppers to prevent skin, eye or nose irritation. You can use peppers in salads, stews, stuffing, relishes and pickling. Sautéed onion and green peppers cut up in strips make a tasty side dish. One raw red pepper can meet the daily requirements for both vitamins A and C."
           ),
           Crop(
            imageName: "squashcrop",
                title: "Squash",
                intro: "Summer squash (Cucurbita pepo) is a warm-season crop that grows best at average temperatures between 65 and 75 °F. Squash seeds do not germinate well in cold soil. In the spring, do not plant this crop until after the last chance of frost has passed, and the soil temperature is 60 ºF, 4-inches below the surface.Squash are very nutritious, have high fiber content and are high in vitamins A and C. Squash are not difficult to grow, so anyone who likes to garden can enjoy them first in the garden and then on the table.",
                types: "nil",
                planting: "Squash plants can be planted from seed or transplants. Plant squash in full sun in rows spaced 3 feet apart. Plant the seeds ½ inch deep and 4 to 6 inches apart in the row. When the seedlings are in the one to two true-leaf stage, thin the plants to 12 to 15 inches apart, selecting the most vigorous ones. Squash transplants should be placed 15 inches apart at planting time. Squash can also be planted in hills. Rows should be spaced 4 to 6 feet apart, with hills 3 to 4 feet apart within the row. Place two or three seeds in each hill. Squash may be grown on black polyethylene mulch. To plant the squash seed, punch a small hole in the plastic and plant. Black polyethylene mulch warms the soil faster in the spring and conserves soil moisture, which usually will result in an earlier harvest. Other advantages of this type of mulch are weed control and reduction of fruit rot. Install a drip irrigation underneath the black polyethylene mulch to provide a uniform supply of water. Use the black mulch only for the spring crop. If the fall crop is grown on polyethylene mulch, paint the mulch white in order to reflect heat. For early squash, use a row cover either alone or in combination with black plastic mulch. The row cover can be either clear polyethylene sheeting supported by wire hoops or one of the spun bonded polyester materials that need no support above the developing plants. For example, a light to medium weight spun-bonded polypropylene will provide 4 degrees of frost protection down to 28º F. Remove these materials before the temperatures get above 75 °F as high temperature under the row covers may inhibit the growth of the plant. ",
                fert: "nil",
                harvest: "Summer squash can be harvested about 55 days after planting. For optimum quality, harvest while fruits are tender and still have a shiny or glossy appearance. When growing conditions are favorable, harvest the crop daily or every other day. Harvest crookneck and straightneck varieties when fruit is 1½ to 2 inches in diameter. Harvest zucchini when fruit is 7 to 8 inches long and scallop types when they are 3 to 4 inches in diameter. If desired, all of these squash can be harvested at smaller sizes for extra tenderness. Do not leave large fruit of summer squash on the plant because this will inhibit the development of additional fruit. Store summer squash in a plastic bag in the refrigerator for up to 1 week."
           ),
           Crop(
            imageName: "cherrytomatoescrop3",
                title: "Cherry Tomato",
                intro: "Tomatoes (Solanum lycopersicum) are a popular staple in Southern vegetable gardens. Tomatoes are warm-season plants that grow best at 70 to 80 °F during the day and 60 to 70 °F during the night.Tomato plants can be set out in the garden in mid-March to early May after any danger of frost has passed. Some southern areas of Georgia can also produce a second crop of tomatoes when planted in late July.Tomatoes are warm-season plants that grow best at temperatures of 70 degrees to 80 degrees F and require six to eight hours of sunlight. Choose a sunny location that receives at least eight hours of sunlight each day.When it comes to tomato varieties, the sky is the limit. They come in a large assortment of shapes, sizes and colors. While it is fun to experiment with the new and exotic tomato varieties, this publication will focus on tried and true varieties for our state. Regardless of which plants you choose, you will need to be familiar with some terminology to make the right choices. ",
                types: "Cherry and grape tomatoes are small, very sweet tomatoes that are often used fresh in salads. Beefsteak tomatoes have large fruit that are commonly sliced and eaten fresh. These tend to be very juicy and are great for tomato sandwiches. Roma or plum tomatoes have medium-sized, oblong fruits with very meaty interiors and few seeds. Romas are a favorite for cooking and canning. ",
                planting: "Select only healthy transplants for planting in the garden. Tomatoes can develop roots all along their stems so plant them deeply to encourage a strong root system. Set the transplants down to the first set of true leaves near the soil surface. If transplants are in peat pots, it is not necessary to remove the container, but be sure to plant them deep enough so the pot is not exposed to the soil surface, causing the root ball to dry out. Firm the soil around the plants to force out any air pockets.Give tomatoes a light amount of fertilizer at planting time. This can be accomplished by using a starter solution of fertilizer. Pour about 1 pint of starter solution (2 tablespoons of 5-10-10 or 5-10-5 fertilizer dissolved in 1 gallon of water) around each plant.If plants are to be staked or trellised, space them 24 inches apart in rows 4 to 6 feet apart. Although it requires more work initially, staking makes caring for tomatoes easier and keeps the plant’s leaves from contacting the ground and possibly introducing disease. This in turn produces higher quality fruit.Staking can be done using commercially available cages or by using 6-foot tall, 1-inch square wooden stakes. Drive wooden stakes into the ground about 1 foot deep and 4 to 6 inches from the transplants. Heavy twine or strips of cloth can be used to tie the plants to the stake about every 10 inches vertically as the plants grow. Tomatoes can also be supported by training them to trellises or using a weaving system of cord and stakes.",
                fert: "A soil test is always the best method of determining the fertilization needs of the crop. Follow the soil test results to maintain a soil pH between 6.0 and 6.5.Apply lime and pre-plant fertilizer according to soil test recommendations. Lime is best applied and tilled into the garden at least 3 months before planting. Broadcast the fertilizer evenly and incorporate it into the soil by tilling or disking to a depth of around 6 inches. Working the fertilizer into the soil ensures that the nutrients are available to the plants when they are transplanted.Side dress 1 pound of calcium nitrate (15.5-0-0) per 100 square feet (30 feet of row) three to four weeks after planting. On sandier soil, this may need to be split into two applications three to four weeks apart to reduce fertilizer losses to leaching. To avoid burning the roots, side-dress fertilizer 4 to 6 inches away from the plants. If fertilizer is broadcast, avoid burning the plant foliage by watering overhead after the application to wash fertilizer granules off the leaves.",
                harvest: "Because the tomato plant is a vine, staking, caging, and trellising are good ways to keep the plants and fruit up and off the ground. Being off the ground makes fruit easier to pick, easier to spray, and improves airflow around the plants, which is an important disease management strategy. Use wooden stakes 6 feet tall and 1 ½ or 2 inches wide for staking. Drive them 1 foot into the soil about 4 to 6 inches from the plant soon after transplanting. Wrap heavy twine or strips of cloth around plant stems and attach to the stakes at every 10 inches of height."
           ),
           Crop(
            imageName: "eggplantcrop",
                title: "Eggplant",
                intro: "Eggplant (Solanum melongena) was introduced into the United States by Thomas Jefferson, who brought this heat-loving member of the Solanaceus family from Europe. While the original eggplants actually looked white, similar to chicken eggs, they now come in many shapes, sizes and colors. Eggplant can be grown in all gardens, and with some care, the harvest can be quite prolific. They can also be grown in containers for their ornamental and decorative features.",
                types: "Standard Italian eggplant varieties produce oval-shaped, glossy, purple-black fruit that is 6 to 9 inches long. Asian eggplant varieties vary in color and shape (elongated, oval, or round), have thinner skin, and more delicate flavor. Specialty eggplants come in a variety of other shapes, sizes, and colors, including red, orange, white, and green. Italian types: Black Magic, Classic, Dusky, Epic, Night Shadow, Santana. Asian types: Ichiban (purple, elongated), Calliope (white and purple, oval), Kermit (green and white, round). Specialty: Casper (white, elongated), Ghostbuster (white, oval), Gretel (white, mini, elongated), Hansel (purple, mini, elongated), Millionaire (purple, elongated) ",
                planting: "Eggplant (Solanum melongena) is a warm-season vegetable that grows best when temperatures are between 70 to 85 °F. It generally has a long growing season and grows slowly during cool periods. Plant in the spring after the last chance of frost and the soil has thoroughly warmed. Set out 6 to 8-week-old transplants to get a head start toward harvest. Seeds germinate quickly at soil temperatures between 70 to 90 °F.",
                fert: "Eggplant requires moderate amounts of fertilizer. A soil test is always the best method of determining the fertilization needs of the crop. Follow the results of a soil test to maintain a soil pH between 6.0 and 6.5.Apply preplant fertilizer according to soil test recommendations. Broadcast the fertilizer evenly and incorporate it into the soil by tilling or discing to a depth of around 6 inches. Working the fertilizer into the soil ensures that the nutrients are available to the plants when they are transplanted.Side dress plants with 5 pounds of calcium nitrate (15.5-0-0) per 1000 square feet or 300 feet of row three to four weeks after planting. For smaller gardens, use ½ pound of calcium nitrate fertilizer per 100 square feet or 30 feet of row. A pint is roughly equal to a pound for most fertilizers. Side dress another 5 pounds per 1000 square feet or ½ pound per 100 square feet three to four weeks after that. To avoid burning the roots, place side-dress fertilizer 4 to 6 inches away from the plants. If fertilizer is broadcast, avoid burning the plant foliage by watering overhead after the application to wash any fertilizer granules off the leaves.Purchased transplants from a local garden center can also be used. Eggplants thrive in warm soils, so wait to purchase plants until the danger of frost has passed and the weather is consistently sunny and warm. The soil temperature should reach 65-70°F before planting the transplants in the garden. Eggplants need a well-drained soil that receives eight to 10 hours of sunlight per day. Water the garden to provide a uniform moisture supply to the crop. Water sufficiently to moisten the soil to a depth of at least 6 inches. The critical period for soil moisture is during fruit set and fruit development. Mulching can help retain consistent soil moisture, conserve water, and reduce weeds.",
                harvest: "Eggplants should be ready for harvest in about 65 to 80 days after transplanting, depending on the variety. When starting from seed, expect 100 to 120 days to reach maturity. Eggplant may be harvested at any time after they have reached sufficient size but should be removed from the plants before the flesh becomes tough, and seeds begin to harden. Italian eggplant should be large, shiny, and a uniform purple color. When the side of the fruit is pressed slightly with the thumbnail, and an indentation remains, the fruit is ripe.Japanese eggplant may be ready to harvest when the size of a finger or hot dog. Typically, eggplants are harvested at least once per week, sometimes twice. The stems of eggplant are tough and heavy; therefore, harvest the fruit by cutting stems with a sharp knife or hand pruners.Harvested eggplant will store in the refrigerator for a week. The optimal conditions for storage are temperatures of 45 to 50 °F and 90-percent relative humidity. "
           ),
           Crop(
            imageName: "cucumbercrop",
                title: "Cucumber",
                intro: "Cucumbers are one of the most popular crops in today's home garden. There are two types of cucumbers that can be grown–those for fresh slicing and those for pickling. Although they require substantial growing space, they can still be grown in small gardens by training vines onto vertical structures or in containers that conserve garden space. The cucumber ranges in size from the small gherkin type to the long, thin slicing variety. As a gardener, you can choose from the many varieties available to suit your needs.",
                types: "nil",
                planting: "Cucumber (Cucumis sativus) is a warm-season vegetable that grows best at temperatures between 75 and 85 °F. Cucumbers are very tender and can be killed by light frosts. Start cucumbers in the garden by planting seed or transplants.Plant seed or transplants after the fear of frost has passed, and the soil temperature has reached 70 °F. Seeds will not germinate at soil temperatures below 50 °F. Seeds may be started indoors two to three weeks prior to planting outdoors.  Spring and fall crops may be grown. ",
                fert: "Cucumbers require moderate amounts of fertilizer. A soil test is always the best method for determining the fertilization needs of the crop. Follow the results of a soil test to maintain a soil pH between 6.0 and 6.5 and optimal fertility levels. If a recent soil test has not been taken, make a preplant application of 5-10-10 at the rate of 3 pounds per 100 square feet. This initial preplant application will normally supply all of the phosphorus and potash needed by most garden vegetables. In the coastal areas of South Carolina, there may be sufficient levels of phosphorus present, a preplant application of 15-0-15 should be used. Before the vines start to develop, sidedress with 34-0-0 at 1 pound per 100 feet of row or calcium nitrate (15.5-0-0) at 2 pounds per 100 feet of row. More frequent sidedressing may be required if the garden is sandy or if leaching rains occur. Do not over fertilize with nitrogen as this encourages excess vine growth and reduces fruit production. Apply fertilizer along one side of the row and about 4 to 6 inches from the plants depending on their size.Cucumbers have a shallow root system and can suffer when no irrigation is provided during droughts. Practice good cultivation and provide adequate water to moisten the soil to at least a 6 inch depth. It is important to provide a uniform moisture supply to the crop as this is critical during fruit set and development. To aid in preventing disease, water at the base of the plant in the morning and avoid wetting the foliage. Mulching helps provide uniform moisture, conserves water, and reduces weeds. Spring-planted cucumbers can be harvested earlier if mulched with soil-warming black plastic. Organic materials, such as pine straw or bark mulch, are useful in the summer to keep the fruit clean in non-trellised plantings.",
                harvest: "Cucumbers are ready for harvest 50 to 70 days from planting, depending on the variety. Depending on their use, harvest on the basis of size. Cucumbers taste best when harvested in the immature stage (Figure 2). Cucumbers should not be allowed to reach the yellowish stage as they become bitter with size. Harvest by cutting the stem 1/4\"above the fruit. Do not trample the vines any more than necessary to harvest the crop.Frequent picking of cucumbers is essential as they grow and reach optimum quality. Delayed harvest results in reduced quality products and less productive plants because fruiting is an exhaustive process for the plant. Harvested cucumbers should be stored in the refrigerator."
           )
        
    ]
}
